import 'package:idealmart/models/product_model.dart';
import 'package:idealmart/views/splash_screen.dart';

List<Product> products = [
  Product("Maggi Masala", 40, "assets/maggi.jpg", 55),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Salt 1 kg", 29, "assets/salt.jpg", 35),
  Product("Aashirvaad Atta", 45, "assets/flour.jpg", 55),
  Product("Kurkure", 20, "assets/kurkure.jpg", 25),
  Product("Sugar Pure", 55, "assets/sugar.jpg", 58),
  Product("Tomato Ketchup", 165, "assets/ketchup.jpg", 185),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Maggi Masala", 40, "assets/maggi.jpg", 55),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Salt 1 kg", 29, "assets/salt.jpg", 35),
  Product("Aashirvaad Atta", 45, "assets/flour.jpg", 55),
  Product("Kurkure", 20, "assets/kurkure.jpg", 25),
  Product("Sugar Pure", 55, "assets/sugar.jpg", 58),
  Product("Tomato Ketchup", 165, "assets/ketchup.jpg", 185),
  Product("Aashirvaad Atta", 45, "assets/flour.jpg", 55),
  Product("Tomato Ketchup", 165, "assets/ketchup.jpg", 185),
  Product("Maggi Masala", 19, "assets/maggi.jpg", 22),
  Product("Tomato Ketchup", 165, "assets/kurkure.jpg", 185),
  Product("Maggi Masala", 40, "assets/maggi.jpg", 55),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Salt 1 kg", 29, "assets/salt.jpg", 35),
  Product("Aashirvaad Atta", 45, "assets/flour.jpg", 55),
  Product("Kurkure", 20, "assets/kurkure.jpg", 25),
  Product("Sugar Pure", 55, "assets/sugar.jpg", 58),
  Product("Tomato Ketchup", 165, "assets/ketchup.jpg", 185),
  Product("Kurkure", 20, "assets/kurkure.jpg", 25),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Tomato Ketchup", 165, "assets/ketchup.jpg", 185),
  Product("Aashirvaad Atta", 45, "assets/flour.jpg", 55),
  Product("Maggi Masala", 1.99, "assets/maggi.jpg", 55),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Sugar Pure", 55, "assets/sugar.jpg", 58),
  Product("Maggi Masala", 40, "assets/maggi.jpg", 55),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Salt 1 kg", 29, "assets/salt.jpg", 35),
  Product("Aashirvaad Atta", 45, "assets/flour.jpg", 55),
  Product("Kurkure", 20, "assets/kurkure.jpg", 25),
  Product("Maggi Masala", 40, "assets/maggi.jpg", 55),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Salt 1 kg", 29, "assets/salt.jpg", 35),
  Product("Aashirvaad Atta", 45, "assets/flour.jpg", 55),
  Product("Kurkure", 20, "assets/kurkure.jpg", 25),
  Product("Sugar Pure", 55, "assets/sugar.jpg", 58),
  Product("Tomato Ketchup", 165, "assets/ketchup.jpg", 185),
  Product("Sugar Pure", 55, "assets/sugar.jpg", 58),
  Product("Tomato Ketchup", 165, "assets/ketchup.jpg", 185),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Sugar Pure", 55, "assets/sugar.jpg", 58),
  Product("Sugar Pure", 1.49, "assets/sugar.jpg", 55),
  Product("Kissan Tomato Ketchup", 2.99, "assets/ketchup.jpg", 55),
  Product("Maggi Masala", 40, "assets/maggi.jpg", 55),
  Product("Moong Dal Split", 99, "assets/moong.jpg", 110),
  Product("Salt 1 kg", 29, "assets/salt.jpg", 35),
  Product("Aashirvaad Atta", 45, "assets/flour.jpg", 55),
  Product("Kurkure", 20, "assets/kurkure.jpg", 25),
  Product("Sugar Pure", 55, "assets/sugar.jpg", 58),
Product("Tomato Ketchup", 165, "assets/ketchup.jpg", 185),  
  Product("Kurkure", 1.49, "assets/kurkure.jpg", 55),
  Product("Maggi Masala", 1.99, "assets/maggi.jpg", 55),
  Product("Sugar Pure", 55, "assets/sugar.jpg", 58),
  Product("Salt 1 kg", 2.99, "assets/salt.jpg", 55),
  Product("Sugar Pure", 1.49, "assets/sugar.jpg", 55),

  // Add more products here
];
